### PR TITLE
Fix for #35. Handling the requirements file properly

### PR DESCRIPTION
**Pull request by shettyh**

### CODE REVIEW

**Comment by alecmerdler** [comment]
Thanks for the PR! We are in the process of adding continuous integration and testing for PRs, will get back to you once it is set up.

**Comment by alecmerdler** [comment]
We have added TravisCI to the repo, you can rebase your PR to run tests now.

**Comment by shettyh** [comment]
Updated the PR branch from `master`

**Comment by jzelinskie** [comment]
This change looks pretty reasonable. Do we really need to block this on CI @alecmerdler?

**Pull request merged**
